name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: /client
    environment:
    - PYTHONUNBUFFERED=1
    - CLI_ID=1
    - FILE_PATH=/agency-1.csv
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  client2:
    container_name: client2
    depends_on:
    - server
    entrypoint: /client
    environment:
    - PYTHONUNBUFFERED=1
    - CLI_ID=2
    - FILE_PATH=/agency-2.csv
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - AMMOUNT_CLIENTS=2
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
